---
- hosts: qgis-server
  sudo: true
  tasks:
   - name: Install ZIP
     apt: pkg=unzip

   - name: Add postgres repository
     apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main' state=present

   - name: Add postgres repository key
     apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present

   - command: apt-get update

   - name: Install postgresql
     apt: pkg=postgresql-9.6 state=present force=yes

   - name: Install PG Packages
     apt: >
       pkg={{item}}
       state=installed
       update-cache=yes
     with_items:
       - build-essential
       - python-dev
       - python-setuptools
       - python-psycopg2
       - postgresql-contrib-9.6
       - postgresql-9.6-postgis-2.3
       - libpq-dev
    
   - command: apt-get add-apt-repository ppa:ubuntugis/ubuntugis-unstable
   - command: apt-get update

   - name: postgresql conf
     lineinfile: dest=/etc/postgresql/9.6/main/postgresql.conf state=present regexp="^listen_addresses = \'*\'*" insertbefore="^port = 5432" line="listen_addresses = \'*\'"         # what IP address(es) to listen on;"

   - name: pg_hba.conf
     lineinfile: dest=/etc/postgresql/9.6/main/pg_hba.conf state=present regexp="host    all             all             0.0.0.0/0            md5" insertbefore="^# IPv6 local connections:" line="host    all             all             0.0.0.0/0            md5"

   - name: Start postgresql server
     service: name=postgresql state=restarted enabled=yes