---
- hosts: qgis-server
  become_user: root
  tasks:
  - name: Add Oracle Java Repository
    become: yes
    apt_repository: repo='ppa:webupd8team/java'

  - name: Accept Java 7 License
    become: yes
    debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Install Oracle Java 7
    become: yes
    apt: name={{item}} state=latest
    with_items:
      - oracle-java7-installer
      - ca-certificates
      - oracle-java7-set-default

  - shell: echo JAVA_HOME is $JAVA_HOME
    environment:
      JAVA_HOME: /usr/lib/jvm/java-7-oracle
    register: shellout
  - debug: var=shellout

  - name: Install Tomcat 7.
    apt: pkg=tomcat7 state=installed
    become: yes

  - stat: path=/var/lib/tomcat7/webapps/geoserver.war
    register: gs_exists

  - copy: src=install_imageio_jai.sh dest=/tmp mode=0777

  - name: Install jai  and imageio
    command: /bin/bash /tmp/install_imageio_jai-ubuntu-14.sh
    become: yes

  - name: download geoserver
    get_url:
      url: http://netix.dl.sourceforge.net/project/geoserver/GeoServer/2.8.5/geoserver-2.8.5-war.zip
      dest: /tmp/geoserver.war.zip
    when: gs_exists.stat.exists == False

  - name: install geoserver
    unarchive: 
      src: /tmp/geoserver.war.zip
      dest: /var/lib/tomcat7/webapps/
      copy: no
    become: yes
    when: gs_exists.stat.exists == False

  - file: path=/tmp/geoserver.war.zip state=absent
    become: yes

  - name: Restart tomcat
    service: 
      name: tomcat7
      state: restarted
    become: yes
