---
- hosts: qgis-server
  become_user: root
  tasks:
  - name: Add Oracle Java Repository
    become: yes
    apt_repository: repo='ppa:webupd8team/java'

  - name: Accept Java 8 License
    become: yes
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Install Oracle Java 8
    become: yes
    apt: name={{item}} state=latest
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default

  - stat: path=/var/lib/tomcat8/webapps/geoserver.war
    register: gs_exists

  - copy: src=install_imageio_jai.sh dest=/tmp mode=0777

  - name: Install jai  and imageio
    command: /bin/bash /tmp/install_imageio_jai.sh
    become: yes

  - name: Install Tomcat 8.
    apt: pkg=tomcat8 state=present
    when: gs_exists.stat.exists == False
    become: yes

  - debug: var=gs_exists.stat.exists

  - stat: path=/tmp/geoserver.war.zip
    register: geoserver_war_stat

  - name: download geoserver
    get_url:
      url: https://newcontinuum.dl.sourceforge.net/project/geoserver/GeoServer/2.13.1/geoserver-2.13.1-war.zip
      dest: /tmp/geoserver.war.zip
    when: gs_exists.stat.exists == False

  - name: install geoserver
    unarchive: 
      src: /tmp/geoserver.war.zip
      dest: /var/lib/tomcat8/webapps/
      copy: no
    become: yes
    when: gs_exists.stat.exists == False

  - file: path=/tmp/geoserver.war.zip state=absent
    become: yes

  - name: Restart tomcat
    service: 
      name: tomcat8
      state: restarted
    become: yes
