---
- hosts: qgis-server
  become_user: root
  tasks:
  - name: Add Oracle Java Repository
    become: yes
    apt_repository: repo='ppa:webupd8team/java'

  - name: Accept Java 8 License
    become: yes
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Install Oracle Java 8
    become: yes
    apt: name={{item}} state=latest
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default

  - name: Install jai
    command: cd /tmp
    become: yes

  - name: Install jai
    command: "{{ item }}" chdir=/tmp
    whith_items:
      wget http://download.java.net/media/jai/builds/release/1_1_3/jai-1_1_3-lib-linux-amd64.tar.gz
      gunzip -c jai-1_1_3-lib-linux-amd64.tar.gz | tar xf - && mv /tmp/jai-1_1_3/lib/*.jar /usr/lib/jvm/java-8-oracle/jre/lib/ext/
      mv /tmp/jai-1_1_3/lib/*.so /usr/lib/jvm/java-8-oracle/jre/lib/amd64/
      rm /tmp/jai-1_1_3-lib-linux-amd64.tar.gz
      rm -r /tmp/jai-1_1_3
    become: yes

  - name: Install imageio
    command: "{{ item }}" chdir=/tmp
    whith_items:
      wget http://download.java.net/media/jai-imageio/builds/release/1.1/jai_imageio-1_1-lib-linux-amd64.tar.gz
      gunzip -c jai_imageio-1_1-lib-linux-amd64.tar.gz | tar xf -
      mv /tmp/jai_imageio-1_1/lib/*.jar /usr/lib/jvm/java-8-oracle/jre/lib/ext/
      mv /tmp/jai_imageio-1_1/lib/*.so /usr/lib/jvm/java-8-oracle/jre/lib/amd64/
      rm /tmp/jai_imageio-1_1-lib-linux-amd64.tar.gz && rm -r /tmp/jai_imageio-1_1
    become: yes

  - name: Install Tomcat 8.
    apt: pkg=tomcat8 state=installed
    become: yes
 
  - stat: path=/tmp/geoserver.war.zip
    register: geoserver_war_stat

  - name: download geoserver
    get_url:
      url: http://heanet.dl.sourceforge.net/project/geoserver/GeoServer/2.9.2/geoserver-2.9.2-war.zip
      dest: /tmp/geoserver.war.zip

  - file: path=/var/lib/tomcat8/webapps/geoserver.war state=absent
    become: yes

  - file: path=/var/lib/tomcat8/webapps/geoserver state=absent
    become: yes

  - name: install geoserver
    unarchive: 
      src: /tmp/geoserver.war.zip
      dest: /var/lib/tomcat8/webapps/
      copy: no
    become: yes

  - file: path=/tmp/geoserver.war.zip state=absent
    become: yes

  - name: Restart tomcat
    service: 
      name: tomcat8
      state: restarted
    become: yes
