---
- hosts: qgis-server
  tasks:
  - name: Install add-apt-repostory
    sudo: true
    apt: name=software-properties-common state=latest

  - name: Add Oracle Java Repository
    sudo: true
    apt_repository: repo='ppa:webupd8team/java'

  - name: Accept Java 8 License
    sudo: true
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Install Oracle Java 8
    sudo: true
    apt: name={{item}} state=latest
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default

  - name: Install Tomcat 8.
    apt: pkg=tomcat8 state=installed
    sudo: true
 
  - stat: path=/tmp/geoserver.war.zip
    register: geoserver_war_stat

  - name: download geoserver
    get_url:
      url: http://netix.dl.sourceforge.net/project/geoserver/GeoServer/2.9.2/geoserver-2.9.2-war.zip
      dest: /tmp/geoserver.war.zip

  - file: path=/var/lib/tomcat8/webapps/geoserver.war state=absent
    sudo: true

  - file: path=/var/lib/tomcat8/webapps/geoserver state=absent
    sudo: true

  - name: install geoserver
    unarchive: 
      src: /tmp/geoserver.war.zip
      dest: /var/lib/tomcat8/webapps/
      copy: no
    sudo: true

  - name: Restart tomcat
    service: 
      name: tomcat8
      state: restarted
    sudo: true
