---
- hosts: qgis-server
  tasks:
  - name: Add Java repo
    apt_repository: repo='ppa:webupd8team/java' state=present update_cache=yes
    sudo: true

  - name: Install oracle-java8-installer
    apt: pkg=oracle-java8-installer state=installed
    sudo: true

  - name: Install Tomcat 8.
    apt: pkg=tomcat8 state=installed
    sudo: true
 
  - stat: path=/tmp/geoserver.war.zip
    register: geoserver_war_stat

  - name: download geoserver
    get_url:
      url: http://netix.dl.sourceforge.net/project/geoserver/GeoServer/2.9.2/geoserver-2.9.2-war.zip
      dest: /tmp/geoserver.war.zip

  - file: path=/var/lib/tomcat8/webapps/geoserver.war state=absent
    sudo: true

  - file: path=/var/lib/tomcat8/webapps/geoserver state=absent
    sudo: true

  - name: install geoserver
    unarchive: 
      src: /tmp/geoserver.war.zip
      dest: /var/lib/tomcat8/webapps/
      copy: no
    sudo: true

  - name: Restart tomcat
    service: 
      name: tomcat8
      state: restarted
    sudo: true
