---
- hosts: qgis-server
  tasks:
  - name: Install Tomcat 7. 
    apt: "pkg={{ item }} state=installed" 
    sudo: true 
    with_items: 
      - tomcat7 
      - tomcat7-admin
 
  - stat: path=/tmp/geoserver.war.zip
    register: geoserver_war_stat

  - name: download geoserver
    get_url:
      url: http://downloads.sourceforge.net/project/geoserver/GeoServer/2.9.1/geoserver-2.9.1-war.zip?r=http%3A%2F%2Fgeoserver.org%2Frelease%2Fstable%2F&ts=1473616263&use_mirror=vorboss
      dest: /tmp/geoserver.war.zip

  - name: install geoserver
    unarchive: 
      src: /tmp/geoserver.war.zip
      dest: /var/lib/tomcat7/webapps/ 
      copy: no
    sudo: true

  - name: Restart tomcat
    service: 
      name: tomcat7 
      state: restarted 
    sudo: true
