---
- hosts: qgis-server
  tasks:
  - name: Install Tomcat 7. 
    apt: "pkg={{ item }} state=installed"
    sudo: true
    with_items: 
      - tomcat7 
      - tomcat7-admin
 
  - stat: path=/tmp/geoserver.war.zip
    register: geoserver_war_stat

  - name: download geoserver
    get_url:
      url: http://netix.dl.sourceforge.net/project/geoserver/GeoServer/2.9.2/geoserver-2.9.2-war.zip
      dest: /tmp/geoserver.war.zip

  - name: install geoserver
    unarchive: 
      src: /tmp/geoserver.war.zip
      dest: /var/lib/tomcat7/webapps/ 
      copy: no
    sudo: true

  - name: Restart tomcat
    service: 
      name: tomcat7 
      state: restarted
    sudo: true
